# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610e36f2aa3ee2ba03698deaf6d34a21a49cc00899f4d680348ae33491cc0127c0430255461d7b803d4557cf3c4415251aee0a1850080f32b55b8bb1157cc40d

test:
  secret_key_base: 18c10b78868e78f6a4a59bcf42f884f0397eec984c7b3c82a91c3457002940fe7f4d350f60759113b13151cedbfd41416e206322699fb684135d0bc6f05ad84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
